module.exports = [
    {word:'ar', tr:'ع'},
    {word: 'headerTitle', tr: 'PS-App'},
    {word:'headerSubTitle', tr: 'Dispenser Journal'},
    {word:'footerTitle', tr: ''},
    {word:'footerSubTitle', tr: 'Dispenser Journals | Copyrights MAl'},
    {word:'journal', tr: 'Journal'},
    {word:'dispensercounters', tr: 'Dispenser Counters'},
    {word:'previousCounter', tr: 'Previous Counter'},
    {word:'currentCounter', tr: 'Current Counter'},
    {word:'totalAmount', tr: 'T. Amount'},
    {word:'dispenserModalTitle', tr: 'Dispenser'},
    {word:'liters', tr: 'Liters'},
    {word:'subTotal', tr: 'Subtotal'},
    {word:'pump', tr: 'pump'},
    {word:'plus', tr: '+'},
    {word:'log_out', tr: 'Log out'},
    {word:'all_users_tody_at', tr:'All users at'},
    {word:'missing_pumps', tr:'Missing pumps data!'},
    {word:'liter', tr: 'Liter'},
    {word:'saveJournals', tr: 'Save'},
    {word:'date', tr: 'Date'},
    {word:'err_counters_zeros', tr:'Counters cannot be both zeros!'},
    {word:'err_current_not_valid', tr:'Current counter can only be numbers'},
    {word:'err_previous_not_valid', tr:'Previous counter can only be numbers'},
    {word:'err_previous_gt_current', tr:'Current counter can only be greater than the previous'},
    {word:'loginTitle', tr:'Login'},
    {word:'loginName', tr:'Name'},
    {word:'loginPass', tr:'Pass'},
    {word:'loginClickCaption', tr:'Ok'},
    {word:'login_err_attemp', tr: 'Attempt'},
    {word:'err_user_id_empty', tr: 'User name empty!'},
    {word:'err_pwd_empty', tr: 'Password empty!'},
    {word:'logged_as', tr: 'Welcome'},
    {word:'err_user_pwd_notvalid', tr: 'User name and/or password are wrong!'},
    {word:'view', tr:'View'}
];
