module.exports = [
    {word:'date', tr: 'التاريخ'},
    {word:'totalAmount', tr: 'الاجمالي'},
    {word:'saveJournals', tr: 'تخزين'},
    {word:'Petrol', tr: 'بنزين'},
    {word:'Diesel', tr: 'سولار'},
    {word:'Kerosin', tr: 'كيروسين'},
    {word:'Gas', tr: 'غاز'},
    {word:'Sign In', tr:'الدخول'},
    {word:'E-mail', tr:'عنوان البريد الالكتروني'},
    {word:'Password', tr:'كلمة المرور'},
    {word:'login', tr:'دخول'},
    {word:'', tr:''},
    {word:'Attempts', tr:'عدد المحاولات'},
    {word:'log_out', tr: 'خروج'},
    {word:'view', tr:'عرض'},
    {word:'loginTitle', tr:'تسجيل الدخول'},
    {word:'loginName', tr:'الاسم'},
    {word:'loginPass', tr:'كلمة المرور'},
    {word:'loginClickCaption', tr:'موافق'},
    {word:'plus', tr:'+'},
    {word:'ar', tr:'ع'},
    {word:'personnel', tr:'المستلم'},
    {word:'all_users_tody_at', tr:'كل المستخدمين لتاريخ'},
    {word:'admin', tr:'الادارة'},
    {word:'pump', tr:'المضخة'},
    {word:'previousCounter', tr:'القراءة السابقة'},
    {word:'currentCounter', tr:'القراءة الحالية'},
    {word:'dispenserModalTitle', tr:'القراءات'},
    {word:'dispensercounters', tr:'القراءات'},
    {word:'Ok', tr:'موافق'},
    {word:'this_user', tr:'لهذا المستخدم'},
    {word:'and', tr:'و'},
    {word:'Cancel', tr:'إلغاء'},
    {word:'click_view_for_journals_this_date', tr:'إضغط على  عرض  لتعرض بيانات اليومية للتاريخ المختار'},
    {word:'no_journals_this_date', tr:'لا يتوفر بعد بيانات لليومية لهذا التاريخ'},
    {word:'missing_pumps', tr:'بيانات المضخات غير متوفرة! تحدث مع المختص بان قاعدة البيانات بها مشكلة'},
    {word:'err_counters_zeros', tr:'خطأ ـ كلا القراءتين صفر!'},
    {word:'err_current_not_valid', tr:'خطأ ـ القراءة الحالية فيها غير ارقام!'},
    {word:'err_previous_not_valid', tr:'خطأ ـ القراءة  السابقة فيها غير ارقام!'},
    {word:'err_previous_gt_current', tr:'خطأ ـ القراءة الحالية يجب ان تكون اعلى من السابقة!'},
    {word:'Ltr', tr:'لتر'},
    {word:'YR', tr:'ريال'},
    {word:'liters', tr:'لتر'},
    {word:'liter', tr:'لتر'},
    {word:'subTotal', tr:'إجمالي'},
    {word:'footerSubTitle', tr: 'Dispenser Journals | Copyrights MAl'},
    {word:'login_err_attemp', tr: 'محاولة رقم'},
    {word:'err_user_id_empty', tr: 'خطأ! ادخل الاسم'},
    {word:'err_pwd_empty', tr: 'خطأ! ادخل كلمة المرور'},
    {word:'logged_as', tr: 'مرحبا'},
    {word:'err_user_pwd_notvalid', tr: 'خطأ! الاسم وكلمة المرور غير متطابقتان.'}

];